Epoch 1/10 - Training:   3%|███▋                                                                                                                                               | 64/2533 [00:19<12:32,  3.28it/s, loss=0.6]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/exit_hooks.py", line 52, in exc_handler
    traceback.print_exception(exc_type, exc, tb)
  File "/home/yukino/miniconda3/lib/python3.12/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/traceback.py", line 733, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/traceback.py", line 438, in _extract_from_extended_frame_gen
    f.line
  File "/home/yukino/miniconda3/lib/python3.12/traceback.py", line 323, in line
    self._line = linecache.getline(self.filename, self.lineno)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/tokenize.py", line 412, in open
    encoding, lines = detect_encoding(buffer.readline)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/tokenize.py", line 381, in detect_encoding
    first = read_or_stop()
            ^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/tokenize.py", line 339, in read_or_stop
    return readline()
           ^^^^^^^^^^
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/home/yukino/Documents/Code/Visual_base/VQVAE/trainer.py", line 56, in <module>
    for data in pbar:
  File "/home/yukino/.local/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 764, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/Documents/Code/Visual_base/VQVAE/Datasets.py", line 22, in __getitem__
    image = Image.open(img_name).convert('RGB')
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/PIL/Image.py", line 3480, in open
    prefix = fp.read(16)
             ^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x796254be23e0>
Traceback (most recent call last):
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/yukino/miniconda3/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/yukino/miniconda3/lib/python3.12/threading.py", line 1147, in join
    self._wait_for_tstate_lock()
  File "/home/yukino/miniconda3/lib/python3.12/threading.py", line 1167, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
